main.o: main.c 3048.h public.h
timer.o: timer.c 3048.h public.h
sci.o: sci.c 3048.h public.h sci_printf.c
shell.o: shell.c 3048.h public.h command_def.h
command.o: command.c 3048.h public.h
bmp.o: bmp.c public.h
public.o: public.c public.h
